// sidebar
export const SET_CUR_SIDEBAR_INDEX = 'SET_CUR_SIDEBAR_INDEX';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

// login
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

// admin
export const REQUEST_ADMIN = 'REQUEST_ADMIN';
export const REQUEST_ADMIN_SUCCESS = 'REQUEST_ADMIN_SUCCESS';
export const REQUEST_ADMIN_FAIL = 'REQUEST_ADMIN_FAIL';
export const UPDATE_ADMIN = 'UPDATE_ADMIN';
export const UPDATE_ADMIN_SUCCESS = 'UPDATE_ADMIN_SUCCESS';
export const UPDATE_ADMIN_FAIL = 'UPDATE_ADMIN_FAIL';
export const SET_ADMIN = 'SET_ADMIN';

// user
export const REQUEST_USER = 'REQUEST_USER';
export const REQUEST_USER_SUCCESS = 'REQUEST_USER_SUCCESS';
export const REQUEST_USER_FAIL = 'REQUEST_USER_FAIL';
export const REQUEST_USER_LIST = 'REQUEST_USER_LIST';
export const REQUEST_USER_LIST_SUCCESS = 'REQUEST_USER_LIST_SUCCESS';
export const REQUEST_USER_LIST_FAIL = 'REQUEST_USER_LIST_FAIL';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const ADD_USER = 'ADD_USER';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAIL = 'ADD_USER_FAIL';
export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const SET_USER_PAGE_NO = 'SET_USER_PAGE_NO';
export const SET_USER_PAGE_SIZE = 'SET_USER_PAGE_SIZE';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER = 'SET_USER';

// article
export const REQUEST_ARTICLE = 'REQUEST_ARTICLE';
export const REQUEST_ARTICLE_SUCCESS = 'REQUEST_ARTICLE_SUCCESS';
export const REQUEST_ARTICLE_FAIL = 'REQUEST_ARTICLE_FAIL';
export const REQUEST_ARTICLE_LIST = 'REQUEST_ARTICLE_LIST';
export const REQUEST_ARTICLE_LIST_SUCCESS = 'REQUEST_ARTICLE_LIST_SUCCESS';
export const REQUEST_ARTICLE_LIST_FAIL = 'REQUEST_ARTICLE_LIST_FAIL';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAIL = 'ADD_ARTICLE_FAIL';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';
export const SET_ARTICLE_PAGE_NO = 'SET_ARTICLE_PAGE_NO';
export const SET_ARTICLE_PAGE_SIZE = 'SET_ARTICLE_PAGE_SIZE';
export const SET_ARTICLE_ID = 'SET_ARTICLE_ID';
export const SET_ARTICLE = 'SET_ARTICLE';
